'use client';

import { ArrowRight, Bell, Bike, CalendarDays, Check, ChevronRight, ClipboardCheck, Gauge, Menu, Package, Plus, ShieldCheck, Timer, Wrench, X } from 'lucide-react';
import { useEffect, useState } from 'react';

const services = [['General Service','Full inspection, fluids & tune-up','From Rs. 899',Wrench],['Brakes & Safety','Pads, discs, fluid & alignment','From Rs. 499',ShieldCheck],['Tyres & Battery','Fitment, balancing & health check','From Rs. 399',Gauge]] as const;
type Role = 'customer'|'mechanic'|'admin';

export default function Home(){
  const [role,setRole]=useState<Role>('customer'); const [booking,setBooking]=useState(false); const [signin,setSignin]=useState(false); const [message,setMessage]=useState('');
  const complete=(text:string)=>{setBooking(false);setMessage(text);window.setTimeout(()=>setMessage(''),3500)};
  const enter=(next:Role)=>{setRole(next);setSignin(false);document.getElementById('workshop')?.scrollIntoView({behavior:'smooth'});};
  return <main><header><a className="brand" href="#top"><span className="mark"><Wrench size={16}/><b>RM</b></span><span><b>ROYAL</b><i>MECHANICS</i></span></a><nav><a href="#services">Services</a><a href="#how">How it works</a><a href="#workshop">Workshop</a><a href="#contact">Contact</a></nav><div className="actions"><button className="menu" aria-label="Menu"><Menu/></button><button className="outline" onClick={()=>setSignin(true)}>Sign in</button><button className="gold" onClick={()=>setBooking(true)}>Book service <ArrowRight size={16}/></button></div></header>
  <section className="hero" id="top"><div className="copy"><p className="eyebrow"><span/>Two-wheeler service & repair</p><h1>Your bike.<br/><em>Our craft.</em></h1><p>Transparent servicing, trusted mechanics and complete vehicle care - all in one place.</p><div className="cta"><button className="gold large" onClick={()=>setBooking(true)}>Book a service <ArrowRight size={18}/></button><a href="#services">Check service cost <ChevronRight size={17}/></a></div><small><ShieldCheck size={17}/>Digital inspection - Clear approvals - Genuine parts</small></div><div className="art"><div className="halo"/><div className="gear">*</div><div className="bike"><Bike size={175}/><span>CRAFTED CARE</span></div><div className="float"><i/> Live job tracking <ArrowRight size={14}/></div></div></section>
  <section className="workspace" id="workshop"><div className="section-head"><div><p className="eyebrow">Service command centre</p><h2>Everything your bike needs,<br/>at a glance.</h2></div><div className="roles">{(['customer','mechanic','admin'] as Role[]).map(x=><button onClick={()=>setRole(x)} className={role===x?'on':''} key={x}>{x}</button>)}</div></div>{role==='customer'?<Customer openBooking={()=>setBooking(true)}/>:role==='mechanic'?<Mechanic complete={complete}/>:<Admin openBooking={()=>setBooking(true)} complete={complete}/>}</section>
  <section className="services" id="services"><div><p className="eyebrow">Workshop services</p><h2>Precision where it<br/>matters most.</h2></div><div className="service-grid">{services.map(([name,desc,price,Icon])=><article key={name}><span className="service-icon"><Icon size={22}/></span><h3>{name}</h3><p>{desc}</p><footer><b>{price}</b><button onClick={()=>setBooking(true)} aria-label={`Book ${name}`}><ArrowRight size={16}/></button></footer></article>)}</div></section>
  <section className="process" id="how"><p className="eyebrow">How it works</p><div>{[['01','Book your slot','Pick a service, time and service mode.'],['02','We inspect with proof','Tap-based checks, photos and a clear estimate.'],['03','You approve with confidence','No extra work starts without your say-so.'],['04','Ride out renewed','QC checked, invoiced and saved to your Bike Passport.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <footer id="contact"><a className="brand" href="#top"><span className="mark"><Wrench size={16}/><b>RM</b></span><span><b>ROYAL</b><i>MECHANICS</i></span></a><p>Traditional mechanical craftsmanship, powered by a modern service experience.</p><small>Copyright 2026 Royal Mechanics</small></footer>
  {booking&&<Booking close={()=>setBooking(false)} done={()=>complete('Booking created and added to the workshop queue.')}/>} {signin&&<SignIn close={()=>setSignin(false)} enter={enter}/>} {message&&<output className="toast"><Check size={16}/>{message}</output>}</main>;
}

function Customer({openBooking}:{openBooking:()=>void}){const[tab,setTab]=useState('Overview');const nav=(name:string,Icon:typeof Gauge)=><button className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={16}/>{name}</button>;return <div className="dashboard customer"><aside><b>Good afternoon, Arjun</b><div>{nav('Overview',Gauge)}{nav('My garage',Bike)}{nav('Service history',ClipboardCheck)}{nav('Appointments',CalendarDays)}</div><button className="help" onClick={openBooking}>Request roadside help</button></aside><section className="empty-garage"><span><Bike size={44}/></span><p className="eyebrow">{tab==='Overview'?'Your digital bike passport':tab}</p><h3>{tab==='My garage'?'No vehicles in your garage.':'Your garage is ready.'}</h3><p>{tab==='Service history'?'Your completed services will appear here once a vehicle has been serviced.':'Add your first two-wheeler to unlock bookings, service history, inspection reports, and a vehicle health score.'}</p><button className="gold" onClick={openBooking}><Plus size={16}/> Add your vehicle</button></section><section className="side"><div className="health"><label>BIKE HEALTH</label><h3>-<small>/100</small></h3><p>Your health score appears after your first workshop inspection.</p></div><div className="approval"><label>NO PENDING APPROVALS</label><h3>All clear for now.</h3><p>When a mechanic recommends a repair, you will see the evidence, price and decision here.</p></div></section></div>}

function Mechanic({complete}:{complete:(x:string)=>void}){const[action,setAction]=useState('');const actions=['Start inspection','Add issue','Add part','Take photo','Voice note','Update status'];return <div className="dashboard mechanic"><section><p className="eyebrow">Mechanic mode</p><h3>Hello, Rajesh.</h3><p>4 jobs today - 1 waiting for you</p><button className="gold" onClick={()=>setAction('Scan a job QR or enter a job ID below.')}>Scan job QR</button></section><section className="work"><div className="job-top"><div><label>CURRENT JOB</label><h3>Hunter 350 <small>TN 38 BX 2041</small></h3></div><em>IN PROGRESS</em></div><p className="complaint">Chain noise and weak front brake.</p><div className="quick">{actions.map((name,i)=>{const Icon=[ClipboardCheck,Plus,Package,Bike,Bell,Timer][i];return <button onClick={()=>setAction(name)} key={name}><Icon size={20}/><span>{name}</span></button>})}</div>{action&&<form className="action-form" onSubmit={e=>{e.preventDefault();complete(`${action} saved to job RM-2041.`);setAction('')}}><b>{action}</b><input aria-label="Job note" placeholder={action==='Scan a job QR'?'Enter job ID, e.g. RM-2041':'Add a short note'} required/><button className="gold" type="submit">Save <Check size={15}/></button><button className="outline" type="button" onClick={()=>setAction('')}>Cancel</button></form>}<button className="complete" onClick={()=>complete('RM-2041 moved to Quality Check.')}>Send to quality check <ArrowRight size={16}/></button></section></div>}

function Admin({openBooking,complete}:{openBooking:()=>void;complete:(x:string)=>void}){const[view,setView]=useState('board');return <div className="dashboard admin"><section><p className="eyebrow">Workshop overview</p><h3>Monday, 8 September</h3><button className="gold" onClick={openBooking}>Create booking <Plus size={16}/></button><div className="metrics">{[['12','Today bookings'],['07','In workshop'],['02','Waiting approval'],['Rs. 18.4k','Today revenue']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section><section className="board"><div><h3>{view==='board'?'Workshop board':'Inventory requests'}</h3><button onClick={()=>setView(view==='board'?'inventory':'board')}>{view==='board'?'View inventory':'View board'}</button></div>{view==='board'?[['Bay 01','Hunter 350','Rajesh','Service in progress'],['Bay 02','Activa 6G','Suresh','Inspection'],['Bay 03','Available','-','Ready for assignment']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small><em>{x[3]}</em></article>):<form className="action-form" onSubmit={e=>{e.preventDefault();complete('Part request sent to the supplier queue.')}}><label>Part name<input required placeholder="e.g. Front brake pads"/></label><label>Quantity<input required type="number" min="1" defaultValue="1"/></label><button className="gold">Request stock <ArrowRight size={15}/></button></form>}</section><section className="stock"><label>INVENTORY ATTENTION</label><h3>Low stock</h3><div><span>Front brake pads</span><b>3 left</b></div><div><span>10W-40 engine oil</span><b>5 left</b></div><button onClick={()=>setView('inventory')}>Review inventory <ArrowRight size={15}/></button></section></div>}

function Booking({close,done}:{close:()=>void;done:()=>void}){const[step,setStep]=useState(1);const[vehicle,setVehicle]=useState('');const[service,setService]=useState('General Service');const[next,setNext]=useState('');const labels=['Vehicle','Service','Mode','Details','Slot','Confirm'];const advance=()=>{if(step===1&&!vehicle.trim()){setNext('Enter a vehicle name or registration to continue.');return;}setNext('');if(step<6)setStep(step+1);else done();};return <div className="backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Book a service"><button className="close" onClick={close} aria-label="Close booking"><X/></button><p className="eyebrow">Book a service</p><h2>Lets get your bike workshop-ready.</h2><div className="book-steps">{labels.map((x,i)=><span className={i<step?'on':''} key={x}>{i+1}<small>{x}</small></span>)}</div><div className="form">{step===1&&<label>Your vehicle<input value={vehicle} onChange={e=>setVehicle(e.target.value)} placeholder="Vehicle model or registration" autoFocus/></label>}{step===2&&<><label>Choose a service category</label><div className="choices">{services.map(([name])=><button type="button" onClick={()=>setService(name)} className={service===name?'selected':''} key={name}>{name}</button>)}<button type="button" onClick={()=>setService('Custom problem')} className={service==='Custom problem'?'selected':''}>Custom problem</button></div></>}{step===3&&<label>Preferred service mode<select defaultValue="Self drop + pickup"><option>Self drop + pickup</option><option>Pickup + drop</option><option>Service on wheels</option></select></label>}{step===4&&<label>Tell us what you notice<textarea placeholder="For example: brake feels soft, chain makes noise..."/></label>}{step===5&&<label>Choose a preferred time<select defaultValue="Tomorrow, 10:00 AM"><option>Tomorrow, 10:00 AM</option><option>Tomorrow, 2:00 PM</option><option>Saturday, 10:00 AM</option></select></label>}{step===6&&<div className="confirm"><Check size={28}/><h3>Ready to confirm</h3><p>{vehicle} - {service}. You can reschedule before the vehicle is received.</p></div>}{next&&<p className="validation">{next}</p>}</div><div className="form-foot"><button className="outline" onClick={()=>step>1?setStep(step-1):close()}>{step===1?'Cancel':'Back'}</button><button className="gold" onClick={advance}>{step===6?'Confirm booking':'Continue'} <ArrowRight size={16}/></button></div></div></div>}

function SignIn({close,enter}:{close:()=>void;enter:(x:Role)=>void}){const[error,setError]=useState('');const clientId=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;useEffect(()=>{if(!clientId){setError('Google sign-in is not configured for this environment.');return;}const run=()=>{const google=(window as Window & {google?:any}).google;if(!google)return;google.accounts.id.initialize({client_id:clientId,callback:async({credential}:{credential:string})=>{setError('');const response=await fetch('/api/auth/google',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential})});const data=await response.json();if(!response.ok){setError(data.error??'Sign-in failed.');return;}enter(data.viewer.role.toLowerCase());}});google.accounts.id.renderButton(document.getElementById('google-sign-in-button'),{theme:'outline',text:'continue_with',shape:'rect',width:300});};const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=run;document.head.appendChild(script);return()=>script.remove();},[clientId,enter]);return <div className="backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Sign in"><button className="close" type="button" onClick={close} aria-label="Close sign in"><X/></button><p className="eyebrow">Secure access</p><h2>Welcome back.</h2><p>Continue with your approved Google account.</p><div id="google-sign-in-button"/><p className="validation">{error}</p><div className="form-foot"><button type="button" className="outline" onClick={close}>Cancel</button></div></div></div>}
